// The items the regulation has, as their pages show them: generated by `npm run gen-data` (`items.data.json`), typed
// here.

import DATA from '@/data/generated/items.data.json'
import type { ItemId, PokemonId } from '@/data/dex'

export const ITEM_KINDS = ['held', 'berry', 'mega'] as const
export type ItemKind = (typeof ITEM_KINDS)[number]

export interface Item {
  /** Its cell on the icon sheet. */
  icon: number
  kind: ItemKind
  /** A Mega Stone's Megas, by the Pokémon holding it. */
  megas?: Partial<Record<PokemonId, PokemonId>>
  /** The only Pokémon it works for, besides Mega Stones (Ogerpon's masks). */
  users?: PokemonId[]
}

export const ITEMS = DATA as unknown as Record<ItemId, Item>
