// The moves the regulation has, as their pages show them: generated by `npm run gen-data` (`moves.data.json`), typed
// here.

import DATA from '@/data/generated/moves.data.json'
import type { MoveId } from '@/data/dex'
import type { TypeId } from '@/data/types'

export const CATEGORIES = ['physical', 'special', 'status'] as const
export type Category = (typeof CATEGORIES)[number]

/** Showdown's move flags the app shows (`MOVE_FLAGS` in `scripts/gen-data.ts`). */
export const FLAGS = [
  'contact',
  'sound',
  'punch',
  'bite',
  'slicing',
  'pulse',
  'bullet',
  'wind',
  'powder',
  'dance',
  'heal',
  'bypasssub',
  'reflectable',
  'protect',
] as const
export type Flag = (typeof FLAGS)[number]

/** Whom a move hits, as Showdown names it. */
export const TARGETS = [
  'normal',
  'any',
  'randomNormal',
  'allAdjacentFoes',
  'allAdjacent',
  'adjacentAlly',
  'adjacentAllyOrSelf',
  'self',
  'allies',
  'allySide',
  'allyTeam',
  'foeSide',
  'all',
  'scripted',
] as const
export type Target = (typeof TARGETS)[number]

export interface Move {
  type: TypeId
  category: Category
  /** 0 for status moves, and for moves whose power varies (their text says how). */
  power: number
  /** `true` for moves that never miss. */
  accuracy: number | true
  /** As Champions has it, PP Ups included. */
  pp: number
  priority: number
  target: Target
  /** `protect` means it goes through Protect. */
  flags: Flag[]
}

export const MOVES = DATA as unknown as Record<MoveId, Move>

/** Moves that hit more than one Pokémon: their damage is reduced to 0.75× when they do. */
export const isSpread = (m: Move) => m.target === 'allAdjacentFoes' || m.target === 'allAdjacent'
