// The Pokémon the regulation has, as their pages show them: generated by `npm run gen-data` (`pokemon.data.json`),
// typed here. Their learnsets are big, so they load on demand (`loadLearnsets`).

import DATA from '@/data/generated/pokemon.data.json'
import type { AbilityId, ItemId, MoveId, PokemonId } from '@/data/dex'
import type { TypeId } from '@/data/types'

export const STATS = ['hp', 'atk', 'def', 'spa', 'spd', 'spe'] as const
export type StatId = (typeof STATS)[number]

export interface Pokemon {
  types: TypeId[]
  /** Base stats, in `STATS` order. */
  stats: [number, number, number, number, number, number]
  /** In slot order; whether one is hidden is left out, as it makes no difference in competitive play. */
  abilities: AbilityId[]
  /** In kilograms (what Low Kick, Grass Knot and Heavy Slam go by). */
  weight: number
  /** Its cell on the icon sheet. */
  icon: number
  /** Showdown has no gen5 sprite of it yet (some new Megas): its page shows its icon instead. */
  noSprite?: true
  /** For formes: the species and the forme as Showdown labels it ("Mega-Z"). */
  base?: PokemonId
  forme?: string
  mega?: true
  /** A forme battles change it into (Megas, Aegislash-Blade): the one it changes from. */
  battleOnly?: PokemonId
  /** A forme that only looks different (Vivillon's patterns). */
  cosmetic?: true
  /** The item it needs: its Mega Stone, or Ogerpon's mask. */
  item?: ItemId
  /** Legal ones only. */
  prevo?: PokemonId
  evos?: PokemonId[]
}

export const POKEMON = DATA as unknown as Record<PokemonId, Pokemon>

/** Its gen5 sprite, a 96×96 image. */
export const spriteUrl = (id: PokemonId) => `${import.meta.env.BASE_URL}sprites/pokemon/${id}.png`

/** Base stat total. */
export const total = (p: Pokemon) => p.stats.reduce((a, b) => a + b, 0)

/** The species a Pokémon belongs to: itself, or its base species for a forme. */
export const speciesOf = (id: PokemonId): PokemonId => POKEMON[id].base ?? id

/** A Pokémon's name, `name`, split in two: a forme's is its species' plus the forme in brackets ("Garchomp (Mega-Z)"). */
export function splitForme(id: PokemonId, name: string): { species: string; forme?: string } {
  const m = POKEMON[id].base ? /^(.+) \((.+)\)$/.exec(name) : null
  return m ? { species: m[1]!, forme: m[2]! } : { species: name }
}

let learnsets: Promise<Record<PokemonId, MoveId[]>> | undefined

/** Every legal Pokémon's moves the regulation has, loaded once. */
export function loadLearnsets(): Promise<Record<PokemonId, MoveId[]>> {
  return (learnsets ??= import('@/data/generated/pokemon.learnsets.json').then(
    (m) => m.default as unknown as Record<PokemonId, MoveId[]>,
  ))
}

/** A Pokémon's moves, from the learnsets: battle-only formes (Megas) learn what their base forme does. */
export function movesOf(sets: Record<PokemonId, MoveId[]>, id: PokemonId): MoveId[] {
  return sets[id]?.length ? sets[id] : (sets[POKEMON[id]?.battleOnly ?? id] ?? [])
}
